/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Marshaled node returned to JS. Mirrors `core::Node` as a napi object so the
 * whole tree crosses the boundary in one return value (full-marshaling mode).
 */
export interface JsNode {
  nodeType: number
  name: string
  value: string
  namespace: string
  publicId: string
  systemId: string
  attrs: Array<JsAttr>
  children: Array<JsNode>
}
export interface JsAttr {
  name: string
  value: string
  prefix: string
}
/** Parse a full HTML document. Boundary crossed exactly once. */
export declare function parse(html: string): JsNode
/**
 * Parse-only: returns node count, builds no JS tree. For isolating raw parse
 * cost from tree-build + boundary marshaling in benchmarks.
 */
export declare function parseRaw(html: string): number
/**
 * SoA flat buffer: structure as typed arrays, crossed once. JS inflates node
 * objects lazily from this — no eager full-tree allocation. The fast path.
 */
export interface JsSoa {
  nodeType: Uint8Array
  ns: Uint8Array
  tagId: Uint32Array
  parent: Int32Array
  firstChild: Int32Array
  nextSib: Int32Array
  textId: Int32Array
  pubId: Int32Array
  sysId: Int32Array
  attrStart: Int32Array
  attrCount: Uint16Array
  attrName: Array<string>
  attrValue: Array<string>
  attrPrefix: Array<string>
  tagNames: Array<string>
  strings: Array<string>
}
/** Parse a document into the SoA flat buffer (the fast runtime path). */
export declare function parseBuffer(html: string): JsSoa
/**
 * Parse an HTML fragment (innerHTML-style). `context` is the context element:
 * e.g. "body" (default), "td", or namespaced "svg path" / "math ms".
 */
export declare function parseFragment(html: string, context?: string | undefined | null): JsNode
